.TH HN 1 "14 February 2019"
.SH NAME
hn - Fetch and open Hacker News stories
.SH SYNOPSIS
hn [ n1 [ n2 [ n3 ... ] ] ]
.SH DESCRIPTION
Invoked with no arguments, this program will fetch the latest HN
headlines and display them as numbered lines.  Invoking the program
subsequently with one or more title numbers will cause the associated
stories to be opened in the system's default web browser.
.SH FILES
.TP
$HOME/.hn
The list of stories most recently fetched.
.SH AUTHOR
Christopher Simons
